# Generated by Django 4.1.7 on 2023-09-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='edited_fields',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='edited_fields',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
