# Generated by Django 4.1.7 on 2023-11-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_historicalstudent_edited_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudent',
            name='economic_range',
        ),
        migrations.RemoveField(
            model_name='student',
            name='economic_range',
        ),
        migrations.AddField(
            model_name='historicalstudent',
            name='household_income',
            field=models.CharField(choices=[('above Php 35,000', 'above Php 35,000'), ('from Php 18,000 - Php 35,000', 'from Php 18,000 - Php 35,000'), ('from Php 9,000 - Php 18,000', 'from Php 9,000 - Php 18,000'), ('below Php 9,000', 'below Php 9,000')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='household_income',
            field=models.CharField(choices=[('above Php 35,000', 'above Php 35,000'), ('from Php 18,000 - Php 35,000', 'from Php 18,000 - Php 35,000'), ('from Php 9,000 - Php 18,000', 'from Php 9,000 - Php 18,000'), ('below Php 9,000', 'below Php 9,000')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='is_a_dropout',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Yes', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='is_a_four_ps_scholar',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='is_a_working_student',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='is_returnee',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='sem',
            field=models.IntegerField(choices=[('Yearly', 'Yearly'), ('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='strand',
            field=models.CharField(choices=[('STEM', 'STEM'), ('BAM', 'BAM'), ('HESS', 'HESS'), ('SPORTS & ARTS', 'SPORTS & ARTS'), ('TVL', 'TVL'), ('GAS', 'GAS'), ('HE', 'HE'), ('ICT', 'ICT'), ('IA', 'IA'), ('Not Applicable (JHS)', 'Not Applicable (JHS)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_a_dropout',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Yes', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_a_four_ps_scholar',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_a_working_student',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_returnee',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.IntegerField(choices=[('Yearly', 'Yearly'), ('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(choices=[('STEM', 'STEM'), ('BAM', 'BAM'), ('HESS', 'HESS'), ('SPORTS & ARTS', 'SPORTS & ARTS'), ('TVL', 'TVL'), ('GAS', 'GAS'), ('HE', 'HE'), ('ICT', 'ICT'), ('IA', 'IA'), ('Not Applicable (JHS)', 'Not Applicable (JHS)')], max_length=50),
        ),
    ]
