# Generated by Django 4.1.7 on 2023-11-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_historicalstudent_economic_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Dropout', 'Dropout'), ('Transferee', 'Transferee'), ('For Promotion/Retention', 'For Promotion/Retention'), ('For Graduation', 'For Graduation')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Dropout', 'Dropout'), ('Transferee', 'Transferee'), ('For Promotion/Retention', 'For Promotion/Retention'), ('For Graduation', 'For Graduation')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='sem',
            field=models.CharField(choices=[('Yearly', 'Yearly'), ('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(choices=[('Yearly', 'Yearly'), ('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], default='None', max_length=30, null=True),
        ),
    ]
