# Generated by Django 4.1.7 on 2023-11-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_historicalstudent_status_student_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevel',
            name='grade',
            field=models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('Graduates', 'Graduates')], max_length=10, unique=True),
        ),
    ]
