# Generated by Django 4.1.7 on 2023-11-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_historicalstudent_notes_student_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudent',
            name='text',
        ),
        migrations.RemoveField(
            model_name='student',
            name='text',
        ),
    ]
