# Generated by Django 4.1.7 on 2023-11-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_historicalstudent_text_remove_student_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('For Dropout', 'For Dropout'), ('For Promotion', 'For Promotion'), ('For Retention', 'For Retention'), ('For Graduation', 'For Graduation')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='strand',
            field=models.CharField(choices=[('STEM', 'STEM'), ('BAM', 'BAM'), ('HESS', 'HESS'), ('SPORTS & ARTS', 'SPORTS & ARTS'), ('TVL', 'TVL'), ('GAS', 'GAS'), ('HE', 'HE'), ('ICT', 'ICT'), ('IA', 'IA'), ('Not Applicable (JHS)', 'Not Applicable (JHS)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('For Dropout', 'For Dropout'), ('For Promotion', 'For Promotion'), ('For Retention', 'For Retention'), ('For Graduation', 'For Graduation')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(choices=[('STEM', 'STEM'), ('BAM', 'BAM'), ('HESS', 'HESS'), ('SPORTS & ARTS', 'SPORTS & ARTS'), ('TVL', 'TVL'), ('GAS', 'GAS'), ('HE', 'HE'), ('ICT', 'ICT'), ('IA', 'IA'), ('Not Applicable (JHS)', 'Not Applicable (JHS)')], max_length=50, null=True),
        ),
    ]
