# Generated by Django 5.0 on 2024-01-12 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_historicalstudent_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevel',
            name='grade',
            field=models.CharField(choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('Transitioning', 'Transitioning')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='classroom',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data.classroom', verbose_name='Classrooms'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.classroom', verbose_name='Classrooms'),
        ),
    ]
