# Generated by Django 5.0.1 on 2024-01-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_remove_historicalstudent_id_remove_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='last_grade_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_grade_level',
            field=models.IntegerField(null=True),
        ),
    ]
