# Generated by Django 4.1.7 on 2023-08-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_historicalstudent_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudent',
            name='previous_school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='previous_school',
        ),
    ]
