# Generated by Django 5.0.1 on 2024-01-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_historicalstudent_last_grade_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='adviser_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='adviser_contact',
            field=models.IntegerField(null=True),
        ),
    ]
