# Generated by Django 5.0.1 on 2024-01-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_historicalstudent_adviser_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='health_bmi',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='health_bmi',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
