# Generated by Django 5.0.1 on 2024-01-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_historicalstudent_health_bmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='general_average',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='general_average',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
