# Generated by Django 4.1.7 on 2023-08-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_historicalstudent_father_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='mother_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_contact',
            field=models.CharField(max_length=15),
        ),
    ]
