# Generated by Django 5.0.1 on 2024-01-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_historicalstudent_general_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
