# Generated by Django 5.0.1 on 2024-02-02 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_historicalstudent_sex_alter_student_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='birth_place',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='birthday',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='edited_fields',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='father_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='father_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='guardian_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='guardian_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='is_a_dropout',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='is_a_four_ps_scholar',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='is_a_working_student',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='is_returnee',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='last_school_attended',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='last_schoolyear_completed',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='mother_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='mother_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='mother_tongue',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='other_religion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='previous_adviser',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='religion',
            field=models.CharField(choices=[('Christianity', 'Christianity'), ('Roman catholic', 'Roman Catholic'), ('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Judaism', 'Judaism'), ('Sikhism', 'Sikhism'), ('Other', 'Other')], default='other', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='suffix_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_place',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='edited_fields',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_a_dropout',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_a_four_ps_scholar',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_a_working_student',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_returnee',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_school_attended',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_schoolyear_completed',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_tongue',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_religion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_adviser',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Christianity', 'Christianity'), ('Roman catholic', 'Roman Catholic'), ('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Judaism', 'Judaism'), ('Sikhism', 'Sikhism'), ('Other', 'Other')], default='other', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='suffix_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
