# Generated by Django 4.1.7 on 2023-08-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_alter_historicalstudent_mother_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='LRN',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='LRN',
            field=models.CharField(max_length=30),
        ),
    ]
