# Generated by Django 4.1.7 on 2023-08-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_historicalstudent_last_schoolyear_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='guardian_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_contact',
            field=models.CharField(max_length=15),
        ),
    ]
