# Generated by Django 4.1.7 on 2023-08-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_historicalstudent_guardian_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalteacher',
            old_name='tid',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='tid',
            new_name='employee_id',
        ),
    ]
