# Generated by Django 5.0.1 on 2024-02-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_historicalstudent_adviser_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='last_grade_level',
            field=models.CharField(blank=True, choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('Transitioning', 'Transitioning')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_grade_level',
            field=models.CharField(blank=True, choices=[('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9'), ('Grade 10', 'Grade 10'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('Transitioning', 'Transitioning')], max_length=15, null=True),
        ),
    ]
