# Generated by Django 5.0.1 on 2024-03-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_remove_historicalstudent_adviser_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('Transferred In', 'Transferred In'), ('Moved In', 'Moved In'), ('Regular', 'Regular')], default='Regular', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('Transferred In', 'Transferred In'), ('Moved In', 'Moved In'), ('Regular', 'Regular')], default='Regular', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='status',
            field=models.CharField(blank=True, choices=[('Currently Enrolled', 'Currently Enrolled'), ('For Dropout', 'For Dropout'), ('For Promotion', 'For Promotion'), ('For Retention', 'For Retention'), ('For Graduation', 'For Graduation')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('Currently Enrolled', 'Currently Enrolled'), ('For Dropout', 'For Dropout'), ('For Promotion', 'For Promotion'), ('For Retention', 'For Retention'), ('For Graduation', 'For Graduation')], max_length=30, null=True),
        ),
    ]
