# Generated by Django 5.0.1 on 2024-03-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_historicalstudent_g10_general_average_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstudent',
            name='edited_fields',
        ),
        migrations.RemoveField(
            model_name='student',
            name='edited_fields',
        ),
    ]
