# Generated by Django 5.0.1 on 2024-03-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_remove_historicalstudent_edited_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='status',
            field=models.CharField(blank=True, choices=[('Currently Enrolled', 'Currently Enrolled'), ('For Dropout/Transfer', 'For Dropout/Transfer'), ('For Promotion', 'For Promotion'), ('For Retention', 'For Retention'), ('For Graduation', 'For Graduation')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('Currently Enrolled', 'Currently Enrolled'), ('For Dropout/Transfer', 'For Dropout/Transfer'), ('For Promotion', 'For Promotion'), ('For Retention', 'For Retention'), ('For Graduation', 'For Graduation')], max_length=30, null=True),
        ),
    ]
