# Generated by Django 5.0.1 on 2024-04-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_alter_historicalstudent_status_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstudent',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
