# Generated by Django 5.0.1 on 2024-05-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0025_alter_historicalstudent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstudent',
            name='previous_section',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_section',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
